### ISSUE TITLE
Main file missed?

### ISSUE THREAD

**Issue by dragen1860** [sagelywizard/snail#2]
Hi, I saw you implemented some network blocks of TCML, but could you share the training source code as well?
Thanks.

**Comment by sagelywizard** [comment]
TCML? Do you mean SNAIL?

This project was just initially an implementation of the blocks described by the paper, which could be used like any other PyTorch layer.

As far as training code for their benchmarks, I added some of the training code, but I'll add the rest when I'm able to replicate their performance numbers. I've been able to get close, but not quite there.
